In [1]:
import numpy as np
from numpy import genfromtxt
from numpy import array
from numpy import trace

In [2]:
A = genfromtxt('test_A.csv', delimiter = ',')
B = genfromtxt('test_B.csv', delimiter = ',')
C = genfromtxt('test_C.csv', delimiter = ',')

x = genfromtxt('test_x.csv', delimiter = ',')
x = x.reshape((x.size, 1)) 
y = genfromtxt('test_y.csv', delimiter = ',')
y = y.reshape((y.size, 1))
z = genfromtxt('test_z.csv', delimiter = ',')
z = z.reshape((z.size, 1))

print(f"A:\n{A}\n")
print(f"B:\n{B}\n")
print(f"C:\n{C}\n")
print(f"x:\n{x}\n")

A:
[[0. 1. 2.]
 [2. 1. 0.]
 [1. 2. 2.]
 [1. 0. 0.]
 [0. 2. 1.]
 [0. 0. 0.]]

B:
[[0. 2. 1.]
 [1. 2. 2.]
 [2. 2. 0.]
 [2. 2. 0.]
 [0. 2. 1.]
 [0. 1. 1.]]

C:
[[2. 1. 0. 1. 1.]
 [2. 1. 1. 0. 2.]
 [2. 0. 1. 2. 2.]
 [2. 0. 2. 1. 0.]
 [0. 0. 2. 1. 0.]
 [0. 0. 2. 1. 1.]]

x:
[[1.]
 [0.]
 [0.]
 [2.]
 [0.]]



In [3]:
print(A.dot(B.T).dot(C).dot(x))

[[ 62.]
 [ 82.]
 [122.]
 [ 22.]
 [ 88.]
 [  0.]]


In [4]:
#1
print(trace(A.dot(A.T)))

25.0


In [5]:
#2
print(A*B)

[[0. 2. 2.]
 [2. 2. 0.]
 [2. 4. 0.]
 [2. 0. 0.]
 [0. 4. 1.]
 [0. 0. 0.]]


In [6]:
#3
print(trace(x.dot(y.T)))

2.0


In [7]:
#4
print(A.dot(B.T))

[[4. 6. 2. 2. 4. 3.]
 [2. 4. 6. 6. 2. 1.]
 [6. 9. 6. 6. 6. 4.]
 [0. 1. 2. 2. 0. 0.]
 [5. 6. 4. 4. 5. 3.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
#5
print(A.dot(B.T).dot(C).dot(x))

[[ 62.]
 [ 82.]
 [122.]
 [ 22.]
 [ 88.]
 [  0.]]


In [9]:
#6
print(C.dot(x+y))

[[ 7.]
 [ 8.]
 [14.]
 [ 9.]
 [ 7.]
 [ 9.]]


In [10]:
#7
x_original = x.reshape(x.size) 
y_original = y.reshape(y.size)
z_original = z.reshape(z.size)
print(f"L0: {np.linalg.norm(x_original, ord=0)}")
print(f"L1: {np.linalg.norm(x_original, ord=1)}")
print(f"L2: {np.linalg.norm(x_original, ord=2)}")
print(f"L inf: {np.linalg.norm(x_original, ord=np.inf)}")

L0: 2.0
L1: 3.0
L2: 2.23606797749979
L inf: 2.0


In [11]:
#8
print(f"L0: {np.linalg.norm(y_original, ord=0)}")
print(f"L1: {np.linalg.norm(y_original, ord=1)}")
print(f"L2: {np.linalg.norm(y_original, ord=2)}")
print(f"L inf: {np.linalg.norm(y_original, ord=np.inf)}")

L0: 3.0
L1: 5.0
L2: 3.0
L inf: 2.0


In [12]:
#9
print(f"L0: {np.linalg.norm(z_original, ord=0)}")
print(f"L1: {np.linalg.norm(z_original, ord=1)}")
print(f"L2: {np.linalg.norm(z_original, ord=2)}")
print(f"L inf: {np.linalg.norm(z_original, ord=np.inf)}")

L0: 2.0
L1: 3.0
L2: 2.23606797749979
L inf: 2.0
