Professor Wu

DS 4400: Machine Learning I

Ryan Tietjen

9/18/24

**Assignment 1**

## Question 1: Find the transpose for the following matrices and vectors (10 pt)

$ 1. 
\begin{bmatrix}
    7 & 4 & 5 & 6 \\
    2 & 8 & 9 & 7 \\
    1 & 0 & 2 & 3
\end{bmatrix} \hspace{1cm}
2. \begin{bmatrix}
    a & b \\
    c & d \\
    e & f
\end{bmatrix} \hspace{1cm}
3. \begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    2 & 0 & 0 & 8
\end{bmatrix} \hspace{1cm}
4. \begin{bmatrix}
    2 & 2 & 8 & 10 \\
\end{bmatrix} \hspace{1cm}
5. \begin{bmatrix}
    1 \\
    2 \\
    2 \\
    8
\end{bmatrix} \hspace{1cm}
$

1. $
\begin{bmatrix}
    7 & 2 & 1 \\
    4 & 8 & 0 \\
    5 & 9 & 2 \\
    6 & 7 & 3
\end{bmatrix}
$

2. $
\begin{bmatrix}
    a & c & e \\
    b & d & f
\end{bmatrix}
$

3. $
\begin{bmatrix}
    1 & 5 & 2 \\
    2 & 6 & 0 \\
    3 & 7 & 0 \\
    4 & 8 & 8
\end{bmatrix}
$

4. $
\begin{bmatrix}
    2 \\
    2 \\
    8 \\
    10
\end{bmatrix}
$

5. $
\begin{bmatrix}
    1 & 2 & 2 & 8 \\
\end{bmatrix}
$

## Question 2. Perform following operations. If the dimension doesn’t match, just indicate ”dimension mismatch”. (10 pt).

1. $
\begin{bmatrix}
    -4 \\
    -7
\end{bmatrix} - 
\begin{bmatrix}
    7 \\
    3
\end{bmatrix} =
\begin{bmatrix}
    -11 \\
    -10
\end{bmatrix}
$

2. $
\begin{bmatrix}
    -2 \\
    0 \\
    3
\end{bmatrix} +
\begin{bmatrix}
    2 \\
    1 \\
    1
\end{bmatrix} =
\begin{bmatrix}
    0 \\
    1 \\
    4
\end{bmatrix}
$

3. $
\begin{bmatrix}
    1 & 2 & 5
\end{bmatrix} +
\begin{bmatrix}
    -7 \\
    8 \\
    3
\end{bmatrix} = 
$
dimension mismatch

4. $
\begin{bmatrix}
    1 & 2 & 5
\end{bmatrix} +
\begin{bmatrix}
    -7 & 8 & 3
\end{bmatrix} = 
\begin{bmatrix}
    -6 & 10 & 8
\end{bmatrix}
$

5. $
\begin{bmatrix}
    1 \\
    2 \\
    5 \\
    0
\end{bmatrix} +
\begin{bmatrix}
    -1 \\
    1 \\
    3 \\
    3
\end{bmatrix} =
\begin{bmatrix}
    0 \\
    3 \\
    8 \\
    3
\end{bmatrix}
$

## Question 3. Given

$ x =
\begin{bmatrix}
    2 \\
    2 \\
    6
\end{bmatrix} \hspace{1cm}
X = \begin{bmatrix}
    -4 & 7 & 5 \\
    1 & -9 & 2 \\
    8 & 3 & 6
\end{bmatrix} \hspace{1cm}
Y = \begin{bmatrix}
    2 & 4 & 6 \\
    1 & 0 & 13 \\
    -4 & 5 & 5
\end{bmatrix} \hspace{1cm}
Z = \begin{bmatrix}
    4 & -1 & 0 \\
    1 & 1 & 1
\end{bmatrix} \hspace{1cm}
$

## Calculate the following: (10 pt)

# 1\) $x^TXY$

$
x^T =
\begin{bmatrix}
    2 & 2 & 6
\end{bmatrix} \hspace{1cm}
$

$ x^TX = 
\begin{bmatrix}
    2 & 2 & 6
\end{bmatrix}
\begin{bmatrix}
    -4 & 7 & 5 \\
    1 & -9 & 2 \\
    8 & 3 & 6
\end{bmatrix} =
\begin{bmatrix}
    2 \cdot -4  + 2 \cdot 1 + 6 \cdot 8 &
    2 \cdot 7  + 2 \cdot -9 + 6 \cdot 3 &
    2 \cdot 5  + 2 \cdot 2 + 6 \cdot 6
\end{bmatrix} =
\begin{bmatrix}
    42 & 14 & 50
\end{bmatrix}
$

$
x^TXY = 
\begin{bmatrix}
    42 & 14 & 50
\end{bmatrix}
\begin{bmatrix}
    2 & 4 & 6 \\
    1 & 0 & 13 \\
    -4 & 5 & 5
\end{bmatrix} = 
\begin{bmatrix}
    42 \cdot 2 + 14 \cdot 1 + 50 \cdot -4 &
    42 \cdot 4 + 50 \cdot 5 &
    42 \cdot 6 + 14 \cdot 13 + 50 \cdot 5
\end{bmatrix} = 
\boxed{
\begin{bmatrix}
    -102 & 418 & 684
\end{bmatrix}}
$

# 2\) $YX$

$
\begin{bmatrix}
    2 & 4 & 6 \\
    1 & 0 & 13 \\
    -4 & 5 & 5
\end{bmatrix}
\begin{bmatrix}
    -4 & 7 & 5 \\
    1 & -9 & 2 \\
    8 & 3 & 6
\end{bmatrix} =
\begin{bmatrix}
    2 \cdot -4 + 4 \cdot 1 + 6 \cdot 8 & 2 \cdot 7 + 4 \cdot -9 + 6 \cdot 3 & 2 \cdot 5 + 4 \cdot 2 + 6 \cdot 6 \\
    1 \cdot -4 + 0 \cdot 1 + 13 \cdot 8 & 1 \cdot 7 + 0 \cdot -9 + 13 \cdot 3 & 1 \cdot 5 + 0 \cdot 2 + 13 \cdot 6 \\
    -4 \cdot -4 + 5 \cdot 1 + 5 \cdot 8 & -4 \cdot 7 + 5 \cdot -9 + 5 \cdot 3 & -4 \cdot 5 + 5 \cdot 2 + 5 \cdot 6
\end{bmatrix} = 
\boxed{
\begin{bmatrix}
    44 & -4 & 54 \\
    100 & 46 & 83 \\
    61 & -58 & 20
\end{bmatrix}}
$

# 3\) $2X + 2Y + X^TY$

$
2X = \begin{bmatrix}
    -8 & 14 & 10 \\
    2 & -18 & 4 \\
    16 & 6 & 12
\end{bmatrix} \hspace{1cm}
2Y = \begin{bmatrix}
    4 & 8 & 12 \\
    2 & 0 & 26 \\
    -8 & 10 & 10
\end{bmatrix} \hspace{1cm}
X^T = \begin{bmatrix}
    -4 & 1 & 8 \\
    7 & -9 & 3 \\
    5 & 2 & 6
\end{bmatrix}
$

$
2X + 2Y = 
\begin{bmatrix}
    -4 & 22 & 22 \\
    4 & -18 & 30 \\
    8 & 16 & 22
\end{bmatrix} \hspace{2cm}
X^TY = 
\begin{bmatrix}
    -4 & 1 & 8 \\
    7 & -9 & 3 \\
    5 & 2 & 6
\end{bmatrix}
\begin{bmatrix}
    2 & 4 & 6 \\
    1 & 0 & 13 \\
    -4 & 5 & 5
\end{bmatrix} =
\begin{bmatrix}
    -39 & 24 & 29 \\
    -7 & 43 & -60 \\
    -12 & 50 & 86
\end{bmatrix} 
$

$
2X + 2Y + X^TY = 
\begin{bmatrix}
    -4 & 22 & 22 \\
    4 & -18 & 30 \\
    8 & 16 & 22
\end{bmatrix} + 
\begin{bmatrix}
    -39 & 24 & 29 \\
    -7 & 43 & -60 \\
    -12 & 50 & 86
\end{bmatrix} =
\boxed{
\begin{bmatrix}
    -43 & 46 & 51 \\
    -3 & 25 & -30 \\
    -4 & 66 & 108
\end{bmatrix}}
$

# 4\) $YZ^T$

$
Z^T = \begin{bmatrix}
    4 & 1 \\
    -1 & 1 \\
    0 & 1
\end{bmatrix}
$

$
YZ^T = 
\begin{bmatrix}
    2 & 4 & 6 \\
    1 & 0 & 13 \\
    -4 & 5 & 5
\end{bmatrix}
\begin{bmatrix}
    4 & 1 \\
    -1 & 1 \\
    0 & 1
\end{bmatrix} =
\begin{bmatrix}
    2 \cdot 4 + 4 \cdot -1 & 2 \cdot 1 + 4 \cdot 1 + 6 \cdot 1 \\
    1 \cdot 4 & 1 \cdot 1 + 13 \cdot 1\\
    -4 \cdot 4 + 5 \cdot -1 & -4 \cdot 1 + 5 \cdot 1 + 5 \cdot 1
\end{bmatrix} =
\boxed{
\begin{bmatrix}
    4 & 12 \\
    4 & 14 \\
    -21 & 6
\end{bmatrix}}
$

# 5\) $Z^TZx$

$
Z^T = \begin{bmatrix}
    4 & 1 \\
    -1 & 1 \\
    0 & 1
\end{bmatrix}
$

$
Zx = 
\begin{bmatrix}
    4 & -1 & 0 \\
    1 & 1 & 1
\end{bmatrix}
\begin{bmatrix}
    2 \\
    2 \\
    6
\end{bmatrix} =
\begin{bmatrix}
    4 \cdot 2 + -1 \cdot 2 \\
    2 + 2 + 6
\end{bmatrix} =
\begin{bmatrix}
    6 \\
    10
\end{bmatrix}
$

$
Z^TZx = 
\begin{bmatrix}
    4 & 1 \\
    -1 & 1 \\
    0 & 1
\end{bmatrix}
\begin{bmatrix}
    6 \\
    10
\end{bmatrix} =
\begin{bmatrix}
    4 \cdot 6 + 10 \\
    -1 \cdot 6 + 10 \\
    10
\end{bmatrix} =
\boxed{
\begin{bmatrix}
    34 \\
    4 \\
    10
\end{bmatrix}}
$

## Question 4. Given

$
X = \begin{bmatrix}
    -4 & 7 & 5 \\
    1 & -9 & 2 \\
    8 & 3 & 6
\end{bmatrix} \hspace{1cm}
Y = \begin{bmatrix}
    0 & 4 & 6 & -8 \\
    1 & -3 & 5 & 7 \\
    11 & 13 & 9 & 9 \\
    -1 & 0 & 8 & 7
\end{bmatrix} \hspace{1cm}
Z = \begin{bmatrix}
    0 & 4 & 8 & 1 \\
    -3 & 5 & 17 & 11 
\end{bmatrix} \hspace{1cm}
A = \begin{bmatrix}
    1 & 17 \\
    2 & 14
\end{bmatrix} \hspace{1cm}
$

$
b = \begin{bmatrix}
    19 & -11 & 13 
\end{bmatrix} \hspace{1cm}
c = \begin{bmatrix}
    12 \\
    -11 \\
    10
\end{bmatrix} \hspace{1cm}
x = \begin{bmatrix}
    1 \\
    2 \\
    3
\end{bmatrix} \hspace{1cm}
y = \begin{bmatrix}
    3 & 3 & 1 
\end{bmatrix} \hspace{1cm}
$

In [1]:
import autograd.numpy as np
from autograd.numpy import log
from autograd.numpy import exp
from autograd import grad
from numpy import trace

In [2]:
X = np.array([[-4, 7, 5],
             [1, -9, 2],
             [8, 3, 6]])
Y = np.array([[0, 4, 6, -8],
             [1, -3, 5, 7],
             [11, 13, 9, 9],
             [-1, 0, 8, 7]])
Z = np.array([[0, 4, 8, 1],
             [-3, 5, 17, 11]])
A = np.array([[1, 17],
             [2, 14]])
b = np.array([[19, -11, 13]])
c = np.array([[12],
             [-11],
             [10]])
x = np.array([[1],
             [2],
             [3]])
y = np.array([[3, 3, 1]])

# Calculate both by hand and by numpy the following (20 pt):

# 1\) $xyy^Tx^T$

$
x^T = \begin{bmatrix}
    1 & 2 & 3
\end{bmatrix} \hspace{1cm}
y^T = \begin{bmatrix}
    3 \\
    3 \\
    1
\end{bmatrix} \hspace{1cm}
$

$
xy = 
\begin{bmatrix}
    1 \\
    2 \\
    3
\end{bmatrix}
\begin{bmatrix}
    3 & 3 & 1 
\end{bmatrix} = 
\begin{bmatrix}
    3 & 3 & 1 \\
    6 & 6 & 2 \\
    9 & 9 & 3
\end{bmatrix} 
$

$
xyy^T = 
\begin{bmatrix}
    3 & 3 & 1 \\
    6 & 6 & 2 \\
    9 & 9 & 3
\end{bmatrix} 
\begin{bmatrix}
    3 \\
    3 \\
    1
\end{bmatrix} = 
\begin{bmatrix}
    3 \cdot 3 + 3 \cdot 3 + 1 \cdot 1\\
    6 \cdot 3 + 6 \cdot 3 + 2 \cdot 1 \\
    9 \cdot 3 + 9 \cdot 3 + 3 \cdot 1
\end{bmatrix} = 
\begin{bmatrix}
    19 \\
    38 \\
    57
\end{bmatrix}
$

$
xyy^Tx^T = 
\begin{bmatrix}
    19 \\
    38 \\
    57
\end{bmatrix}
\begin{bmatrix}
    1 & 2 & 3
\end{bmatrix} =
\boxed{
\begin{bmatrix}
    19 & 38 & 57 \\
    38 & 76 & 114 \\
    57 & 114 & 171
\end{bmatrix}}
$

In [3]:
print(x.dot(y).dot(y.T).dot(x.T))

[[ 19  38  57]
 [ 38  76 114]
 [ 57 114 171]]


# 2\) 3c - 9

$
3c - 9 = 3
\begin{bmatrix}
    12 \\
    -11 \\
    10
\end{bmatrix} - 9 = 
\begin{bmatrix}
    36 \\
    -33 \\
    30
\end{bmatrix} - 9 =
\boxed{
\begin{bmatrix}
    27 \\
    -42 \\
    21
\end{bmatrix}}
$

In [4]:
print((3*c) - 9)

[[ 27]
 [-42]
 [ 21]]


# 3\) $\langle A, A \rangle \cdot A$

$
A^T = \begin{bmatrix}
    1 & 2 \\
    17 & 14
\end{bmatrix}
$

$
AA^T = 
\begin{bmatrix}
    1 & 17 \\
    2 & 14
\end{bmatrix}
\begin{bmatrix}
    1 & 2 \\
    17 & 14
\end{bmatrix} = 
\begin{bmatrix}
    1 \cdot 1 + 17 \cdot 17 & 1 \cdot 2 + 17 \cdot 14 \\
    2 \cdot 1 + 14 \cdot 17 & 2 \cdot 2 + 14 \cdot 14
\end{bmatrix} = 
\begin{bmatrix}
    290 & 240 \\
    240 & 200
\end{bmatrix}
$

trace(
$
AA^T
$) $= 290 + 200 = 490$

$
490 \cdot
\begin{bmatrix}
    1 & 17 \\
    2 & 14
\end{bmatrix} = 
\boxed{
\begin{bmatrix}
    490 & 8330 \\
    980 & 6860
\end{bmatrix} }
$

In [5]:
print(trace(A.dot(A.T)) * (A))

[[ 490 8330]
 [ 980 6860]]


# 4\) $2XZ$

dimension mismatch :O

In [6]:
try:
    print(2 * X.dot(Z))
except ValueError as e:
    print("Error:", e)

Error: shapes (3,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)


# 5\) $(bc)A$

$
\begin{bmatrix}
    19 & -11 & 13 
\end{bmatrix}
\begin{bmatrix}
    12 \\
    -11 \\
    10
\end{bmatrix} =
19 \cdot 12 + -11 \cdot -11 + 13 \cdot 10 = 479
$

$
479 \cdot
\begin{bmatrix}
    1 & 17 \\
    2 & 14
\end{bmatrix} = 
\boxed{
\begin{bmatrix}
    479 & 8143 \\
    958 & 6706
\end{bmatrix}}
$

In [7]:
print(b.dot(c) * (A))

[[ 479 8143]
 [ 958 6706]]


# 6\) $bXA$

$
XA = $dimension mismatch :O
$

In [8]:
try:
    print(b.dot(X).dot(A))
except ValueError as e:
    print("Error:", e)

Error: shapes (1,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


# 7\) $c\odot x$

$
\begin{bmatrix}
    12 \\
    -11 \\
    10
\end{bmatrix} \odot
\begin{bmatrix}
    1 \\
    2 \\
    3
\end{bmatrix} = 
\begin{bmatrix}
    12 \cdot 1 \\
    -11 \cdot 2 \\
    10 \cdot 3
\end{bmatrix} =
\boxed{
\begin{bmatrix}
    12 \\
    -22 \\
    30
\end{bmatrix}}
$

In [9]:
print(c * x)

[[ 12]
 [-22]
 [ 30]]


# 8\) $b\odot y$

$
\begin{bmatrix}
    19 & -11 & 13 
\end{bmatrix} \odot
\begin{bmatrix}
    3 & 3 & 1 
\end{bmatrix} =
\begin{bmatrix}
    19 \cdot 3 & -11 \cdot 3 & 13 \cdot 1 
\end{bmatrix} = 
\boxed{
\begin{bmatrix}
    57 & -33 & 13 
\end{bmatrix}}
$

In [10]:
print(b * y)

[[ 57 -33  13]]


# 9\) $c \otimes x$

$
cx^T = 
\begin{bmatrix}
    12 \\
    -11 \\
    10
\end{bmatrix}
\begin{bmatrix}
    1 & 2 & 3
\end{bmatrix} = 
\begin{bmatrix}
    12 \cdot 1 & 12 \cdot 2 & 12 \cdot 3 \\
    -11 \cdot 1 & -11 \cdot 2 & -11 \cdot 3 \\
    10 \cdot 1 & 10 \cdot 2 & 10 \cdot 3 
\end{bmatrix}=
\boxed{
\begin{bmatrix}
    12 & 24 & 36 \\
    -11 & -22 & -33 \\
    10 & 20 & 30
\end{bmatrix}
}
$

In [11]:
print(c.dot(x.T))

[[ 12  24  36]
 [-11 -22 -33]
 [ 10  20  30]]


# 10\) $YZ^T$

$
Z^T = 
\begin{bmatrix}
    0 & 3 \\
    4 & 5 \\
    8 & 17 \\
    1 & 11
\end{bmatrix}
$

$
YZ^T = 
\begin{bmatrix}
    0 & 4 & 6 & -8 \\
    1 & -3 & 5 & 7 \\
    11 & 13 & 9 & 9 \\
    -1 & 0 & 8 & 7
\end{bmatrix}
\begin{bmatrix}
    0 & 3 \\
    4 & 5 \\
    8 & 17 \\
    1 & 11
\end{bmatrix} = 
\begin{bmatrix}
    0 \cdot 0 + 4 \cdot 4 + 6 \cdot 8 + -8 \cdot 1 & 0 \cdot 3 + 4 \cdot 5 + 6 \cdot 17 + -8 \cdot 11  \\
    1 \cdot 0 + -3 \cdot 4 + 5 \cdot 8 + 7 \cdot 1 & 1 \cdot 3 + -3 \cdot 5 + 5 \cdot 17 + 7 \cdot 11 \\
    11 \cdot 0 + 13 \cdot 4 + 9 \cdot 8 + 9 \cdot 1 & 11 \cdot 3 + 13 \cdot 5 + 9 \cdot 17 + 9 \cdot 11 \\
    -1 \cdot 0 + 0 \cdot 4 + 8 \cdot 8 + 7 \cdot 1 & -1 \cdot 3 + 0 \cdot 5 + 8 \cdot 17 + 7 \cdot 11
\end{bmatrix} =
\boxed{
\begin{bmatrix}
    56 & 34 \\
    35 & 144 \\
    133 & 284 \\
    71 & 216
\end{bmatrix}
}
$

In [12]:
print(Y.dot(Z.T))

[[ 56  34]
 [ 35 144]
 [133 284]
 [ 71 216]]


## Question 5. Write the code that performs the following operations using numpy. Make sure you print the results. (20 pt)

• Create two matrices and two vectors

$
X = \begin{bmatrix}
    2 & 3 \\
    9 & 1
\end{bmatrix} \hspace{1cm}
Y = \begin{bmatrix}
    1 & 0 \\
    2 & 1
\end{bmatrix} \hspace{1cm}
x = \begin{bmatrix}
    1 \\
    3 
\end{bmatrix} \hspace{1cm}
y = \begin{bmatrix}
    2 \\
    4 
\end{bmatrix} \hspace{1cm}
$

In [13]:
X = np.array([[2, 3],
             [9, 1]])
Y = np.array([[1, 0],
             [2, 1]])
x = np.array([[1],
             [3]])
y = np.array([[2],
             [4]])

• Write the code that extracts the 1st column of $X$.

In [14]:
print(X[:, 0])

[2 9]


• Write the code that extracts the 2nd row of $Y$.

In [15]:
print(Y[1,:])

[2 1]


• Write the code that extracts the bottom right value of $X$.

In [16]:
print(X[-1, -1])

1


• Write the code that adds $X + Y$.

In [17]:
print(X + Y)

[[ 3  3]
 [11  2]]


• Write the code that performs $X + YX$.

In [18]:
print(X + Y.dot(X))

[[ 4  6]
 [22  8]]


• Write the code that performs the Hadamard product $x$ ⊙ $y$.

In [19]:
print(x*y)

[[ 2]
 [12]]


• Write the code that performs the outer product $x$ ⊗ $y$.

In [20]:
print(x.dot(y.T))

[[ 2  4]
 [ 6 12]]


• Write the code that performs the dot product $XY$.

In [21]:
print(X.dot(Y))

[[ 8  3]
 [11  1]]


• Write the code that performs the inner product $⟨X, Y⟩$.

In [22]:
print(trace(X.dot(Y.T)))

21


## Question 6. (20 pt) Given vectors

$
v = \begin{bmatrix}
    5 \\
    0 \\
    0
\end{bmatrix} \hspace{1cm}
w = \begin{bmatrix}
    8 \\
    1 \\
    1
\end{bmatrix} \hspace{1cm}
x = \begin{bmatrix}
    3 \\
    1 \\
    2
\end{bmatrix} \hspace{1cm}
y= \begin{bmatrix}
    2\\
    1 \\
    0 \\
    3
\end{bmatrix} \hspace{1cm}
z= \begin{bmatrix}
    2 \\
    5
\end{bmatrix}
$

• For each vector, calculate the L1-norm, L2-norm and L-infinity norm.

• Once you have calculated the norms, use numpy to show that your calculation is correct.

In [23]:
v = np.array([5, 0, 0])
w = np.array([8, 1, 1])
x = np.array([3, 1, 2])
y = np.array([2, 1, 0, 3])
z = np.array([2, 5])

$||v||_1 = |5| + |0| + |0| = 5$

$||v||_2 = \sqrt{(5^2 + 0^2 + 0^2)} = 5$

$||v||_\infty = max(5, 0, 0) = 5$

In [24]:
print(f"v: L1 norm: {np.linalg.norm(v, ord=1)}")
print(f"v: L2 norm: {np.linalg.norm(v, ord=2)}")
print(f"v: L inf norm: {np.linalg.norm(v, ord=np.inf)}")

v: L1 norm: 5.0
v: L2 norm: 5.0
v: L inf norm: 5.0


$||w||_1 = |8| + |1| + |1| = 10$

$||w||_2 = \sqrt{(8^2 + 1^2 + 1^2)} = \sqrt{66} \approx 8.12$

$||w||_\infty = max(8, 1, 1) = 8$

In [25]:
print(f"w: L1 norm: {np.linalg.norm(w, ord=1)}")
print(f"w: L2 norm: {np.linalg.norm(w, ord=2)}")
print(f"w: L inf norm: {np.linalg.norm(w, ord=np.inf)}")

w: L1 norm: 10.0
w: L2 norm: 8.12403840463596
w: L inf norm: 8.0


$||x||_1 = |3| + |1| + |2| = 6$

$||x||_2 = \sqrt{(3^2 + 1^2 + 2^2)} = \sqrt{14} \approx 3.74$

$||x||_\infty = max(3, 1, 2) = 3$

In [26]:
print(f"x: L1 norm: {np.linalg.norm(x, ord=1)}")
print(f"x: L2 norm: {np.linalg.norm(x, ord=2)}")
print(f"x: L inf norm: {np.linalg.norm(x, ord=np.inf)}")

x: L1 norm: 6.0
x: L2 norm: 3.7416573867739413
x: L inf norm: 3.0


$||y||_1 = |2| + |1| + |0| + |3| = 6$

$||y||_2 = \sqrt{(2^2 + 1^2 + 0^2 + 3^2)} = \sqrt{13} \approx 3.74$

$||y||_\infty = max(3, 1, 0, 2) = 3$

In [27]:
print(f"y: L1 norm: {np.linalg.norm(y, ord=1)}")
print(f"y: L2 norm: {np.linalg.norm(y, ord=2)}")
print(f"y: L inf norm: {np.linalg.norm(y, ord=np.inf)}")

y: L1 norm: 6.0
y: L2 norm: 3.7416573867739413
y: L inf norm: 3.0


$||z||_1 = |2| + |5|= 7$

$||z||_2 = \sqrt{(2^2 + 5^2)} = \sqrt{29} \approx 5.385$

$||z||_\infty = max(2, 5) = 5$

In [28]:
print(f"z: L1 norm: {np.linalg.norm(z, ord=1)}")
print(f"z: L2 norm: {np.linalg.norm(z, ord=2)}")
print(f"z: L inf norm: {np.linalg.norm(z, ord=np.inf)}")

z: L1 norm: 7.0
z: L2 norm: 5.385164807134504
z: L inf norm: 5.0


## Question 7. (10 pt) Use Numpy to write the code that loads hw1.csv file and print out the data matrix. Please show the code as well as the output. The file hw1.csv should be in the general data/HW1 folder.

In [29]:
from numpy import genfromtxt
data = genfromtxt('hw1.csv', delimiter = ',')
print(data)

[[1. 2. 1.]
 [2. 0. 0.]
 [2. 1. 1.]
 [1. 2. 5.]]
