In [3]:
import numpy as np
from numpy import array
from numpy import trace

In [17]:
x = np.array([[2],[6]])
print(f"x:\n{x}\n")

y = np.array([[1],[0]])
print(f"y:\n{y}\n")

X = np.array([[7,5],[3,6]])
print(f"X:\n{X}\n")

Y = np.array([[2,4],[1,0]])
print(f"Y:\n{Y}\n")

Z = np.array([[4, -1, 0],[1,1,1]])
print(f"Z:\n{Z}\n")

x:
[[2]
 [6]]

y:
[[1]
 [0]]

X:
[[7 5]
 [3 6]]

Y:
[[2 4]
 [1 0]]

Z:
[[ 4 -1  0]
 [ 1  1  1]]



In [38]:
#1

trace(x.dot(x.T)) + x.T.dot(y)

array([[42]])

In [44]:
#2
#x.dot(y.T)
np.outer(x, y)

array([[2, 0],
       [6, 0]])

In [42]:
#3
Y*X

array([[14, 20],
       [ 3,  0]])

In [26]:
#4
2*X + 2*Y + X.T.dot(Y)

array([[35, 46],
       [24, 32]])

In [45]:
#5
trace(Y.dot(Y.T))

21

In [28]:
#6
Z.dot(Z.T).dot(x)

array([[52],
       [24]])