In [1]:
import autograd.numpy as np
from autograd import grad

In [2]:
def f_one(x, y, one):
    return np.dot(np.transpose(y), x) + np.dot(np.transpose(x), one)

def dx_f_one(x, y, one):
    return y + one

auto_grad = grad(f_one)

y = np.array([[2],[5]])
one = np.array([[1],[1]])

for i in range(3):
    x = np.random.random((2,1))
    print("Auto gradient:\n",auto_grad(x, y, one))
    print("Theoretical gradient:\n", dx_f_one(x, y, one))


Auto gradient:
 [[3.]
 [6.]]
Theoretical gradient:
 [[3]
 [6]]
Auto gradient:
 [[3.]
 [6.]]
Theoretical gradient:
 [[3]
 [6]]
Auto gradient:
 [[3.]
 [6.]]
Theoretical gradient:
 [[3]
 [6]]


In [3]:
def f_two(x, A):
    return np.dot(np.dot(np.transpose(x), A), x)

def dx_f_two(x, A):
    return np.dot(2*A, x)

auto_grad = grad(f_two)

A = np.array([[2, 1],[1, 1]])

for i in range(3):
    x = np.random.random((2,1))
    print("Auto gradient:\n",auto_grad(x, A))
    print("Theoretical gradient:\n", dx_f_two(x, A))


Auto gradient:
 [[1.993571  ]
 [1.08290876]]
Theoretical gradient:
 [[1.993571  ]
 [1.08290876]]
Auto gradient:
 [[4.9682638 ]
 [3.35565243]]
Theoretical gradient:
 [[4.9682638 ]
 [3.35565243]]
Auto gradient:
 [[5.20182848]
 [3.43952869]]
Theoretical gradient:
 [[5.20182848]
 [3.43952869]]


In [4]:
def f_three(x, A):
    return np.exp(np.dot(np.dot(np.transpose(x), A), x))

def dx_f_three(x, A):
    return (np.exp(np.dot(np.dot(np.transpose(x), A), x)) * np.dot((np.transpose(A) + A), x))
    

auto_grad = grad(f_three)

A = np.array([[4, 0],[1, 1]])

for i in range(3):
    x = np.random.random((2,1))
    print("Auto gradient:\n",auto_grad(x, A))
    print("Theoretical gradient:\n", dx_f_three(x, A))


Auto gradient:
 [[4.33932044]
 [4.12037077]]
Theoretical gradient:
 [[4.33932044]
 [4.12037077]]
Auto gradient:
 [[8.38420141]
 [1.19304005]]
Theoretical gradient:
 [[8.38420141]
 [1.19304005]]
Auto gradient:
 [[201.77558816]
 [ 32.62460935]]
Theoretical gradient:
 [[201.77558816]
 [ 32.62460935]]


In [5]:
def f_four(x, w):
    return 1/(1+np.exp(-np.dot(np.transpose(w),x)))
    

def dx_f_four(x, w):
    temp = np.exp(np.dot(np.transpose(w), x)) 
    numer = temp
    denom = (1 + temp)**2
    return (numer / denom) * w
    
auto_grad = grad(f_four)

w = np.array([[7],[8]])


for i in range(3):
    x = np.random.random((2,1))
    print("Auto gradient:\n",auto_grad(x, w))
    print("Theoretical gradient:\n", dx_f_four(x, w))


Auto gradient:
 [[0.00066767]
 [0.00076305]]
Theoretical gradient:
 [[0.00066767]
 [0.00076305]]
Auto gradient:
 [[0.00026719]
 [0.00030536]]
Theoretical gradient:
 [[0.00026719]
 [0.00030536]]
Auto gradient:
 [[0.00401289]
 [0.00458617]]
Theoretical gradient:
 [[0.00401289]
 [0.00458617]]
